// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/messageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace messageIdG {

  /// <summary>Holder for reflection information generated from proto/messageId.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/messageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90by9tZXNzYWdlSWQucHJvdG8SCm1lc3NhZ2VJZEcqjgMKCU1lc3Nh",
            "Z2VJZBIICgROb25lEAASFAoOQ1NDcmVhdGVQbGF5ZXIQ0YYDEhQKDlNDQ3Jl",
            "YXRlUGxheWVyENKGAxINCgdDU0xvZ2luENOGAxINCgdTQ0xvZ2luENSGAxIR",
            "CgtDU0FkZEZyaWVuZBChjQYSEQoLU0NBZGRGcmllbmQQoo0GEhEKC0NTRGVs",
            "RnJpZW5kEKONBhIRCgtTQ0RlbEZyaWVuZBCkjQYSEwoNQ1NTZW5kQ2hhdE1z",
            "ZxCljQYSEwoNU0NTZW5kQ2hhdE1zZxCmjQYSHQoXQ2xpZW50UmVxdWVzdE9i",
            "amVjdFN5bmMQypoMEh0KF1NlcnZlclJlcXVlc3RPYmplY3RTeW5jEMuaDBIl",
            "Ch9TZXJ2ZXJSZXF1ZXN0T2JqZWN0U3luY0NvbXBsZXRlEMyaDBIRCgtJbnN0",
            "YW50aWF0ZRDUmgwSDQoHRGVzdHJveRDVmgwSGwoVRGVzdHJveU5ldHdvcmtP",
            "YmplY3RzENaaDBITCg1TeW5jVHJhbnNmb3JtEN6aDEIZWgovbWVzc2FnZUlk",
            "qgIKbWVzc2FnZUlkR2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::messageIdG.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///定义Message消息的id
  /// </summary>
  public enum MessageId {
    /// <summary>
    ///CS: C-->S
    ///SC: S-->C
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///用户创建
    /// </summary>
    [pbr::OriginalName("CSCreatePlayer")] CscreatePlayer = 50001,
    [pbr::OriginalName("SCCreatePlayer")] SccreatePlayer = 50002,
    /// <summary>
    ///客户端登录请求
    /// </summary>
    [pbr::OriginalName("CSLogin")] Cslogin = 50003,
    /// <summary>
    ///服务器响应登录请求
    /// </summary>
    [pbr::OriginalName("SCLogin")] Sclogin = 50004,
    /// <summary>
    ///player
    ///添加好友
    /// </summary>
    [pbr::OriginalName("CSAddFriend")] CsaddFriend = 100001,
    [pbr::OriginalName("SCAddFriend")] ScaddFriend = 100002,
    /// <summary>
    ///删除好友
    /// </summary>
    [pbr::OriginalName("CSDelFriend")] CsdelFriend = 100003,
    [pbr::OriginalName("SCDelFriend")] ScdelFriend = 100004,
    /// <summary>
    ///聊天包
    /// </summary>
    [pbr::OriginalName("CSSendChatMsg")] CssendChatMsg = 100005,
    [pbr::OriginalName("SCSendChatMsg")] ScsendChatMsg = 100006,
    [pbr::OriginalName("ClientRequestObjectSync")] ClientRequestObjectSync = 200010,
    [pbr::OriginalName("ServerRequestObjectSync")] ServerRequestObjectSync = 200011,
    [pbr::OriginalName("ServerRequestObjectSyncComplete")] ServerRequestObjectSyncComplete = 200012,
    [pbr::OriginalName("Instantiate")] Instantiate = 200020,
    [pbr::OriginalName("Destroy")] Destroy = 200021,
    [pbr::OriginalName("DestroyNetworkObjects")] DestroyNetworkObjects = 200022,
    [pbr::OriginalName("SyncTransform")] SyncTransform = 200030,
  }

  #endregion

}

#endregion Designer generated code
